scrape_configs:
  - job_name: 'Spring Boot Application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:4000']
        labels:
          application: 'Spring Boot Application'
    basic_auth:
      username: 'prometheus'
      password: 'prometheus'